version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"

  postgres:
    build:
      context: ./postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
